RH_Admin/Controllers/EntretientController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SIRH.Models;

namespace SIRH.Controllers;

public class EntretientController : Controller
{
    public IActionResult listeBesoin()
    {
        Besoin[] allBesoin = new Besoin().select(null).OfType<Besoin>().ToArray();

        ViewBag.all = allBesoin;

        return View("listeBesoin");
    }
    public IActionResult listeCandidat(int idbesoin)
    {
        double notemin = 10; // note minimun tam test voaray
        List<NCBesoin> ncb = new NoteCandidat().getAllCandidatBesoin(null,notemin,idbesoin);

        ViewBag.AllCandidat = ncb;

        return View("listeCandidat");
    }

    public IActionResult embaucher(int idbesoin,int idcandidat,int idposte,int idtypecontrat,double valeurbrute,double valeurnet,DateTime datedebut,DateTime datefin)
    {
        int idbesoincandidat = new BddObjet().getInteger($"select id from besoin_candidat where idbesoin = {idbesoin} and idcandidat = {idcandidat}", null);
        Embauche embauche = new Embauche(idbesoincandidat, idcandidat, idposte, idtypecontrat, DateTime.Now, 1);
        embauche.insert(null);

        // Console.WriteLine($"{datedebut} / {datefin}");

        int idembauche = new BddObjet().getInteger($"SELECT max(id) FROM embauche", null);

        embauche = new Embauche(idembauche);
        embauche.update($"id = {idembauche}", null);

        Salaire salaire = new Salaire(-1,idembauche,valeurbrute,valeurnet,datedebut,datefin);
        salaire.insert(null);

        return RedirectToAction("listeCandidat",new {idbesoin = idbesoin});
    }
}

RH_Admin/Views/Entretient/listeBesoin.cshtml
<div class="card">
    <div class="card-body">
        <p class="card-title mb-0">Choisissez d'abord un besoin</p>
        <div class="table-responsive">
            <table class="table table-striped table-borderless">
                <thead>
                    <tr>
                        <th>numero besoin</th>
                        <th>libelle</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(Besoin besoin in ViewBag.all){
                        <tr>
                            <td>@besoin.Id</td>
                            <td>@besoin.Libelle</td>
                            <td class="font-weight-medium">
                                <a class="btn btn-primary" href="@Url.Action("listeCandidat", "Entretient", new { idbesoin = @besoin.Id })">
                                    Voir candidats
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

RH_Admin/Views/Entretient/listeCandidat.cshtml
@{
    Boolean isEmpty = true;
}
<div class="row grid-margin stretch-card" id="primary">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Liste des candidats ayant des notes superieur</h4>

            <div class="">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prenom</th>
                            <th>Telephone</th>
                            <th>Poste</th>
                            <th>Note</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (NCBesoin ncb in ViewBag.AllCandidat)
                        {
                            isEmpty = false;
                            <tr>
                                <td>@ncb.Candidat.Nom</td>
                                <td>@ncb.Candidat.Prenom</td>
                                <td>@ncb.Candidat.Telephone</td>
                                <td>@ncb.Poste.Libelle</td>
                                <td>@ncb.NoteCandidat.Note</td>
                                <td>
                                    <a href="#" class="text-secondary" data-toggle="modal" data-target="#addContrat" onclick="javascript:embaucher(@ncb.Besoin.Id,@ncb.Candidat.Id, @ncb.Poste.Id ,@ncb.Besoin.Idtypecontrat)">
                                        <i class="fas fa-handshake menu-icon"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                
                @if(isEmpty) {
                <div class="text-center p-3 text-secondary">
                    <em>Aucun element pour l'instant</em>
                </div>
                }
            </div>
        </div>
    </div>
</div>

<!-- Contrat - Modal -->
<div id="addContrat" class="modal fade" role="dialog" aria-labelledby="addContrat" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="post" asp-controller="Entretient" asp-action="embaucher">
                <div class="modal-header b-0">
                    <h5 class="modal-title title" id="exampleModalLabel">Contrat de la personne</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Brute <input type="text" class="form-control" name="valeurbrute"></p>
                    <p>Net <input type="text" class="form-control" name="valeurnet"></p>
                    <p>Date debut <input type="date" class="form-control" name="datedebut"></p>
                    <p>Date fin<input type="date" class="form-control" name="datefin"></p>
                    <input type="hidden" class="form-control" id="idbesoin" name="idbesoin">
                    <input type="hidden" class="form-control" id="idcandidat" name="idcandidat">
                    <input type="hidden" class="form-control" id="idposte" name="idposte">
                    <input type="hidden" class="form-control" id="idtypecontrat" name="idtypecontrat">
                </div>
                <div class="modal-footer b-0">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-primary">Confirmer</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Fin - Modal -->

<script>
    function embaucher(idbesoin,idcandidat,idposte,idtypecontrat) {
        document.getElementById("idbesoin").value = idbesoin;
        document.getElementById("idcandidat").value = idcandidat;
        document.getElementById("idposte").value = idposte;
        document.getElementById("idtypecontrat").value = idtypecontrat;
    }
</script>