RH_Admin/Models/Employe.cs
using Npgsql;

namespace SIRH.Models
{
    public class Employe : Candidate
    {
        int idembauche;
        String service;
        String poste;
        int idbesoincandidat;
        int etat;
        DateTime dateembauche;

        public string Service { get => service; set => service = value; }
        public string Poste { get => poste; set => poste = value; }
        public DateTime Dateembauche { get => dateembauche; set => dateembauche = value; }
        public int Idbesoincandidat { get => idbesoincandidat; set => idbesoincandidat = value; }
        public int Etat { get => etat; set => etat = value; }
        public int Idembauche { get => idembauche; set => idembauche = value; }

        public Employe()
        {
            this.init();
        }

        public override String tableName()
        {
            return "vw_embauche";
        }

        public Employe(string service, string poste, int idbesoincandidat, DateTime dateembauche)
        {
            this.service = service;
            this.poste = poste;
            this.dateembauche = dateembauche;
            this.idbesoincandidat = idbesoincandidat;
        }

        public Object[] Criteres(NpgsqlConnection cnx)
        {
            Object[] criteres = new CandidatCritere().select($"where idcandidat = {this.idbesoincandidat}", cnx);

            return criteres;
        }

    }
}

RH_Admin/Controllers/EmployeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SIRH.Models;

namespace SIRH.Controllers
{
    public class EmployeController : Controller
    {
        public IActionResult Index()
        {
            Embauche[] em = new Embauche().GetAll(null);
            ViewBag.embauches = em;
            return View();
        }

        public IActionResult Absences()
        {
            Conge[] c = new Conge().GetDemandesConges(null);
            ViewBag.conges = c;
            return View();
        }

        public IActionResult Detail(int id)
        {
            Console.WriteLine(id);
            Object employe = new Employe().Init($"where id = {id}", null);
            Object[] faits = new Faits().select("", null);

            ViewBag.Employe = employe;
            ViewBag.Faits = faits;

            return View("Info");
        }

        public IActionResult AddFait(int idembauche, int count, int action, DateTime datefait)
        {
            if (count > 3)
            {
                BddObjet.ExecuteNonQuery($"update embauche set etat = 0 where id = {idembauche}", null);
            }
            Faits fait = new Faits(-1, idembauche, action, datefait);
            fait.insert(null);

            return Detail(1);
        }
    }
}

RH_Admin/Views/Employe/Absences.cshtml
@{
  Conge[] conges = ViewBag.conges;
  Boolean isEmpty = true;
}
<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="card-title">Journal des conges</p>
        <div class="row">
          <div class="col-12">
              <div class="mb-3 mt-5">
                <ul class="nav">
                    <li>
                        <a class="btn btn-primary" style="width: 150px;" data-toggle="collapse" href="#recherche-employe" aria-expanded="false" aria-controls="form-elements">
                            <span class="menu-title">Recherche</span>
                            <sub><i class="mdi mdi-chevron-down menu-icon"></i></sub>
                        </a>
                        <div class="collapse mt-2" id="recherche-employe">
                            <table class="inputs">
                              <tbody>
                                <tr>
                                  <td>Date minimum:</td>
                                  <td><input type="date" id="min" name="min" class="form-control"></td>
                                </tr>
                                <tr>
                                  <td>Date maximum:</td>
                                  <td><input type="date" id="max" name="max" class="form-control"></td>
                                </tr>
                              </tbody>
                            </table>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="table-responsive">
              <table
                id="absences"
                class="display expandable-table"
                style="width: 100%"
              >
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Salarie</th>
                    <th>Service</th>
                    <th>Type de conges</th>
                    <th>Periode du conge</th>
                    <th>Duree</th>
                    <th>Statut</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach (var item in conges)
                  {
                    <tr>
                      <td>@item.DebutConge.ToString("yyyy-MM-dd")</td>
                      <td>@item.Embauche.Nom @item.Embauche.Prenom</td>
                      <td>@item.Embauche.Poste.Service.Libelle</td>
                      <td>@item.TypeConge.Nom</td>
                      <td>
                        @item.DebutConge.ToShortDateString() -
                        @item.FinConge.ToShortDateString()
                      </td>
                      <td>@item.GetDuree() jour</td>
                      <td class="font-weight-medium">
                        @Html.Raw(item.ShowStatus())
                      </td>
                    </tr>
                  }
                </tbody>
              </table>

              @if(isEmpty) {
                <div class="text-center p-3 text-secondary">
                  <em>Aucun element pour l'instant</em>
                </div>
              }
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="~/js/absences.js"></script>

RH_Admin/Views/Employe/Index.cshtml
@{
  Embauche[] embauches = ViewBag.embauches;
  Boolean isEmpty = true;

}
<div class="row">
  <div class="col-md-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <p class="card-title">Liste des employes</p>
        <div class="row">
          <div class="col-12">
            <div class="table-responsive">
                <div class="mb-3 mt-5">
                  <ul class="nav">
                      <li>
                          <a class="btn btn-primary" style="width: 150px;" data-toggle="collapse" href="#recherche-employe" aria-expanded="false" aria-controls="form-elements">
                              <span class="menu-title">Recherche</span>
                              <sub><i class="mdi mdi-chevron-down menu-icon"></i></sub>
                          </a>
                          <div class="collapse mt-2" id="recherche-employe">
                              <form method="post" asp-controller="Employe" asp-action="Recherche" class="form-inline">
                                  <input type="text" name="motcle" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Mot cle...">
                                  
                                  <div class="input-group mb-2 mr-sm-2">
                                      <select name="etat" class="form-control" id="exampleSelectGender">
                                          <option value="2">Tous</option>
                                          <option value="1">Actif</option>
                                          <option value="0">Non Actif</option>
                                      </select>
                                  </div>
                                  <div class="input-group mb-2 mr-sm-2">
                                      <select name="idservice" class="form-control" id="exampleSelectGender">
                                          <option>Choix service</option>
                                          <option value="0">Tous</option>
                                      </select>
                                  </div>
                                  <button type="submit" class="btn btn-primary mb-2"><i class="icon-search"></i></button>
                              </form>
                          </div>
                      </li>
                  </ul>
              </div>
              <table
                id="example"
                class="display expandable-table"
                style="width: 100%"
              >
                <thead>
                  <tr>
                    <th>N° matricule</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    @* <th>Date de naissance</th> *@
                    @* <th>Date d' embauche</th> *@
                    @* <th>Genre</th> *@
                    <th>Direction</th>
                    <th>Fonction</th>
                    @* <th>Adresse</th> *@
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach (var item in embauches)
                  {
                    isEmpty = false;
                    <tr>
                      <td>@item.Numeromatricule</td>
                      <td>@item.Nom</td>
                      <td>@item.Prenom</td>
                      @* <td>@item.DateNaissance.ToString("yyyy-MM-dd")</td> *@
                      @* <td>@item.DateEmbauche.ToString("yyyy-MM-dd")</td> *@
                      @* <td>@item.ShowGenre()</td> *@
                      <td>@item.Poste.Service.Libelle</td>
                      <td>@item.Poste.Libelle</td>
                      @* <td>@item.Adresse</td> *@
                      <td>
                        <div class="col-md-2 dropdown">
                          <a href='@Url.Action("Detail", "Employe", new{id = item.IdCandidat})'>
                            <i class="mdi mdi-information-outline"></i> 
                          </a>
                        </div>
                      </td>
                    </tr>
                  }
                </tbody>
              </table>

              @if(isEmpty) {
                <div class="text-center p-3 text-secondary">
                    <em>Aucun element pour l'instant</em>
                </div>
              }
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Suppression - Modal -->
<div id="virer-employe" class="modal fade" role="dialog" aria-labelledby="virer-employe" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header b-0">
                <h4 class="modal-title">Message confirmation</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- Modal Body -->
            <div class="modal-body">
                <p>La suppression de certaines elements peuvent etre irreversible, voulez vous continuer ?</p>
            </div>
            <div class="modal-footer b-0">
                <form method="post" asp-controller="Employe" asp-action="Virer">
                    <input type="hidden" id="id-delete" name="idembauche">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i>&nbsp;&nbsp;Annuler</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i>&nbsp;&nbsp;Confirmer</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Modal -->

<script>
    function virer_employe(id) {
        document.getElementById("id-delete").value = id;
    }
</script>
<script src="~/js/listeEmployes.js"></script>

RH_Admin/Views/Employe/ListEmploye.cshtml
@page
@{
    Object[] employes = (Object[]) ViewBag.Employes;
}

<div class="row grid-margin stretch-card"  id="primary">
    <div class="card">
    <div class="card-body">
        <h4 class="card-title">Liste des employes</h4>
        <div class="mb-3 mt-5">
            <ul class="nav">
                <li>
                    <a class="btn btn-primary" style="width: 150px;" data-toggle="collapse" href="#recherche-employe" aria-expanded="false" aria-controls="form-elements">
                        <span class="menu-title">Recherche</span>
                        <sub><i class="mdi mdi-chevron-down menu-icon"></i></sub>
                    </a>
                    <div class="collapse mt-2" id="recherche-employe">
                        <form method="post" asp-controller="Employe" asp-action="Recherche" class="form-inline">
                            <input type="text" name="motcle" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Mot cle...">
                            
                            <div class="input-group mb-2 mr-sm-2">
                                <select name="etat" class="form-control" id="exampleSelectGender">
                                    <option value="2">Tous</option>
                                    <option value="1">Actif</option>
                                    <option value="0">Non Actif</option>
                                </select>
                            </div>
                            <div class="input-group mb-2 mr-sm-2">
                                <select name="idservice" class="form-control" id="exampleSelectGender">
                                    <option>Choix service</option>
                                    <option value="0">Tous</option>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2"><i class="icon-search"></i></button>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <div class="">
        <table class="table">
            <thead>
            <tr>
                <th>Numero</th>
                <th>Poste</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Statut</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (Employe employe in employes) {
            <tr>
                <td>@employe.Id</td>
                <td>@employe.Poste</td>
                <td>@employe.Nom</td>
                <td>@employe.Prenom</td>
                @if(employe.Etat == 1) {
                    <td><label class="badge badge-success">Actif</label></td>
                } else {
                    <td><label class="badge badge-danger">Non Actif</label></td>
                }
                <td>
                    <div class="col-md-2 dropdown">
                        <button class="btn btn-link text-secondary mb-0">
                            <i class="fas fa-ellipsis-v "></i>
                        </button>
                        <div class="dropdown-content border-radius-md shadow">
                            <a asp-area="" asp-controller="Employe" asp-action="Detail">
                                <i class="mdi mdi-information-outline"></i> 
                            </a>
                            <a href="#">
                                <i class="mdi mdi mdi-pen"></i>
                            </a>
                            <a href="#" data-toggle="modal" data-target="#virer-employe" onclick="javascript:virer_employe(@employe.Id)">
                                <i class="mdi mdi-close"></i>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
            }
            </tbody>
        </table>
        </div>
    </div>
    </div>
</div>

<!-- Suppression - Modal -->
<div id="virer-employe" class="modal fade" role="dialog" aria-labelledby="virer-employe" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header b-0">
                <h4 class="modal-title">Message confirmation</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!-- Modal Body -->
            <div class="modal-body">
                <p>La suppression de certaines elements peuvent etre irreversible, voulez vous continuer ?</p>
            </div>
            <div class="modal-footer b-0">
                <form method="post" asp-controller="Employe" asp-action="Virer">
                    <input type="hidden" id="id-delete" name="idembauche">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times"></i>&nbsp;&nbsp;Annuler</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-check"></i>&nbsp;&nbsp;Confirmer</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- End Modal -->

<script>
    function virer_employe(id) {
        document.getElementById("id-delete").value = id;
    }
</script>