RH_Client/Models/Announcement.cs
using Npgsql;

namespace RH_Client.Models
{
    public class Announcement : BddObjet
    {
        int id;
        int idBesoin;
        DateTime dateEnvoi;
        int idEntreprise;
        Besoin besoin;
        Company entreprise;
        Profile[] profilMinimal;

        public Announcement()
        {
            this.init();
        }

        public Announcement(int id, int idBesoin, DateTime dateEnvoi, int idEntreprise, Besoin besoin, Company entreprise, Profile[] profilMinimal)
        {
            Id = id;
            IdBesoin = idBesoin;
            DateEnvoi = dateEnvoi;
            IdEntreprise = idEntreprise;
            Besoin = besoin;
            Entreprise = entreprise;
            ProfilMinimal = profilMinimal;
        }

        public override String tableName()
        {
            return "annonce";
        }

        public int Id { get => id; set => id = value; }
        public int IdBesoin { get => idBesoin; set => idBesoin = value; }
        public DateTime DateEnvoi { get => dateEnvoi; set => dateEnvoi = value; }
        public int IdEntreprise { get => idEntreprise; set => idEntreprise = value; }
        public Besoin Besoin { get => besoin; set => besoin = value; }
        public Company Entreprise { get => entreprise; set => entreprise = value; }
        public Profile[] ProfilMinimal { get => profilMinimal; set => profilMinimal = value; }

        public Announcement Find(NpgsqlConnection con)
        {
            bool isNewConnexion = false;
            if (con == null)
            {
                con = new Connexion().getConnectPostgres();
                isNewConnexion = true;
            }
            try
            {
                Announcement annonce = new Announcement();
                annonce = (Announcement)annonce.select("WHERE id = " + this.Id, null)[0];
                Company c = (Company)new Company().select(con)[0];
                annonce.GetNeed(con);
                annonce.Entreprise = c;
                annonce.GetAllProfile(con);
                return annonce;
            }
            catch (System.Exception)
            {

                throw;
            }
            finally
            {
                if (isNewConnexion == true)
                {
                    con.Close();
                }
            }
        }

        public Announcement[] GetAll(NpgsqlConnection con)
        {
            bool isNewConnexion = false;
            if (con == null)
            {
                con = new Connexion().getConnectPostgres();
                isNewConnexion = true;
            }
            try
            {
                Announcement[] annonces = this.select(con).OfType<Announcement>().ToList().ToArray<Announcement>();
                Company c = (Company)new Company().select(con)[0];
                foreach (var item in annonces)
                {
                    item.GetNeed(con);
                    item.Entreprise = c;
                    item.GetAllProfile(con);
                }
                return annonces;
            }
            catch (System.Exception)
            {

                throw;
            }
            finally
            {
                if (isNewConnexion == true)
                {
                    con.Close();
                }
            }
        }

        public Critere[] GetAllCritere(NpgsqlConnection con)
        {
            bool isNewConnexion = false;
            if (con == null)
            {
                con = new Connexion().getConnectPostgres();
                isNewConnexion = true;
            }
            try
            {
                List<Critere> criteres = new List<Critere>();
                string query = "SELECT besoin_critere.*, critere.libelle, critere.nature FROM besoin_critere JOIN critere ON critere.id = besoin_critere.idcritere";
                Console.WriteLine(query);
                using (var command = new NpgsqlCommand(query, con))
                {
                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            criteres.Add(new Critere(reader.GetInt32(2), reader.GetString(4), reader.GetInt32(5)));
                        }
                    }
                }
                return criteres.ToArray();
            }
            catch (System.Exception)
            {

                throw;
            }
            finally
            {
                if (isNewConnexion == true)
                {
                    con.Close();
                }
            }
        }

        public void GetAllProfile(NpgsqlConnection con)
        {
            bool isNewConnexion = false;
            if (con == null)
            {
                con = new Connexion().getConnectPostgres();
                isNewConnexion = true;
            }
            try
            {
                Critere[] criteres = this.GetAllCritere(con);
                this.ProfilMinimal = new Profile[criteres.Length];
                for (int i = 0; i < criteres.Length; i++)
                {
                    this.ProfilMinimal[i] = new Profile();
                    this.ProfilMinimal[i].Critere = criteres[i];
                    this.ProfilMinimal[i].Option = this.ProfilMinimal[i].Critere.GetMinOption(this.Besoin, con);
                }
            }
            catch (System.Exception)
            {

                throw;
            }
            finally
            {
                if (isNewConnexion == true)
                {
                    con.Close();
                }
            }
        }

        public void GetNeed(NpgsqlConnection con)
        {
            bool isNewConnexion = false;
            if (con == null)
            {
                con = new Connexion().getConnectPostgres();
                isNewConnexion = true;
            }
            try
            {
                this.Besoin = (Besoin)new Besoin().select("WHERE id = " + this.IdBesoin, con)[0];
                this.Besoin.GetJob(con);
                this.Besoin.GetContract(con);
            }
            catch (System.Exception)
            {

                throw;
            }
            finally
            {
                if (isNewConnexion == true)
                {
                    con.Close();
                }
            }
        }
    }
}

RH_Client/Controllers/AnnouncementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RH_Client.Models;

namespace RH_Client.Controllers
{
    public class AnnouncementController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Liste()
        {
            Announcement[] annonces = new Announcement().GetAll(null);
            return View(annonces);
        }
    }
}

RH_Client/Views/Announcement/Index.cshtml
<style>
  /* Styles pour le formulaire de la table "culture" */
  .form-container-quai {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }

  .form-container-quai label {
    font-weight: bold;
  }

  .form-container-quai input[type="text"],
  .form-container-quai input[type="number"],
  .form-container-quai input[type="datetime-local"] {
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  .form-container-quai .btn-primary {
    width: 100%;
    padding: 10px;
  }
</style>

<div class="form-container-quai">
  <form action="@Url.Action("Create", "Announcement")" method="POST">
    @if (ViewBag.message is not null)
	{
		<span style="color: red;">@ViewBag.message</span>
	}
    <label for="id_besoin">Besoin :</label>
    <input type="number" id="id_besoin" name="id_besoin" required>

    <label for="date">Date de creation :</label>
    <input type="datetime-local" id="date" name="date">

    <button type="submit" class="btn btn-primary">Creer</button>
  </form>
</div>

RH_Client/Views/Announcement/Liste.cshtml
@model Announcement[]

<!DOCTYPE html>
<html>
<head>
    <title>Liste des offres d'emploi</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1>Liste des offres d'emploi</h1>
        <div class="row">
            @foreach (var offre in Model)
            {
                <div class="col-md-12 mb-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">@offre.Besoin.Poste.Libelle</h5>
                            <h6 class="card-subtitle mb-2 text-muted">@offre.Entreprise.Nom | @offre.Besoin.Contrat.Libelle</h6>
                            <p class="card-text">@offre.Besoin.Poste.Description</p>
                            <p class="card-text">Date de publication: @offre.DateEnvoi.ToShortDateString()</p>
                            <div class="card-body">
                                <h6 style="color: purple;">PROFIL</h6>
                                @foreach (var item in @offre.ProfilMinimal)
                                {
                                    <p class="card-text">- @item.Critere.Libelle : @item.Option.Libelle</p>
                                }
                            </div>
                            <a class="nav-link" style="color: purple;" asp-area="" asp-controller="CV" asp-action="Index">Liste des postulants</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>
</html>